# Generated by Django 3.2.8 on 2021-10-21 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('bot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
                ('board1', models.CharField(max_length=1)),
                ('board2', models.CharField(max_length=1)),
                ('board3', models.CharField(max_length=1)),
                ('board4', models.CharField(max_length=1)),
                ('board5', models.CharField(max_length=1)),
                ('board6', models.CharField(max_length=1)),
                ('board7', models.CharField(max_length=1)),
                ('board8', models.CharField(max_length=1)),
                ('board9', models.CharField(max_length=1)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bot')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
